# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-depl
  namespace: default
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: amitmahajan/demo-api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: demo-srv
spec:
  selector:
    app: demo-app
  ports:
    - name: demo-app
      protocol: TCP
      port: 8080
      targetPort: 8080